name: 'SAML.to Assume AWS Role'
description: 'GitHub Action Assume AWS Roles using SAML.to'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: The GitHub token
    required: true
  role:
    description: The ARN of the role to assume
    required: true
  region:
    description: The AWS Region
    required: false
    default: 'us-east-1'
  provider:
    description: The provider to use in saml-to.yml
    required: false
outputs:
  region:
    description: The AWS region
  accountId:
    description: The AWS Account ID
  userId:
    description: The Ephemeral User ID
  roleArn:
    description: The ARN of the Role
  assumedRoleArn:
    description: The effective ARN of the Assumed Role
  accessKeyId:
    description: The AWS Access Key ID
  secretAccessKey:
    description: The AWS Secret Access Key
  sessionToken:
    description: The AWS Session Token
runs:
  using: 'node16'
  main: 'dist/main.js'
