name: 'SAML.to Assume AWS Role'
description: 'GitHub Action Assume AWS Roles using SAML.to'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: The GitHub token
    required: true
  role:
    description: The ARN of the role to assume
    required: true
  provider:
    description: The provider to use in saml-to.yml
    required: false
outputs:
  accessKeyId:
    description: The AWS Access Key ID
  secretAccessKey:
    description: The AWS Secret Access Key
  sessionToken:
    description: The AWS Session Token
runs:
  using: 'node16'
  main: 'dist/main.js'
